language: node_js
node_js:
  - '8.10.0'
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir /home/travis/build/dagcoin/dagcoin/cordova/project-ANDROID
  - mkdir /home/travis/build/dagcoin/dagcoin/cordova/project-ANDROID/www
  - sleep 3
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g codecov
  - npm install -g cordova@~7.1.0
  - npm install -g cordova-android@~6.3.0
  - npm install -g phonegap
install:
  - gem install fastlane
  - gem install sass
  - bower install
  - npm install
  - bundle install
script:
  - npm test
  - fastlane beta
#  - codecov --token=f33366c3-862d-4bdf-b956-c9ace7bb9739
cache:
  directories:
    - "node_modules"
    - "bower_components"
notifications:
  slack:
    secure: W1hT6pF0aL46Au6WO5YlnSYUgq+lA96Rr4ybN6aGmTjdhvYgYezMT9QD/EHv+YTgOaeZb8Kx1W0A0cHT8I6F56jt/tN24GUB0BBal7WSAy0XekBww0Ot1edQCXLB6sG/X2qMrN2xVM2e+BOOmRtzdN25l5NVFyHRCTUMEYHDlgYmpiWprluCb8Vcf/bXCs8N6wEgtsFfVFCmnMEhH4Se2IZXf7LYxOCZPG8/udLTheSIgu7mP7paYi2kW1dmdZC3VlRxlkX43NhZiFqBm4zqwZQq6VqT0gnA5G1YErSlw9jP396Qdo8NQSXEPWfTYhVM6e5897N2LX0OdEU4ZfVLsXWGcmbk+vqO4JrcL10MeOokza4fx6IWOntH4m4tal0YW11yjL0nrJBmi7u27eg0fcPc52wvpPRJOs28EXtEv2BdK5wVuXwoIjx5FRDh3QyqTk+gnWUhvwv6at4xcjYYWS4DBZnQAKw/D/bXKt7faELxKNALCHEm6huRXth8F790k1aaVn+5oYwpA7ZrN+z+dvnJUt4dRy0fTh70nPqLfg2AULEo8Al6ss/U110ogEKJ6Qg8EIFR0X7M6A2olcFEYCMnCnN5TalGTmq+ope9HQ/nwBodY07W/F0iXx+EpuIscS00dlWccCsn/YrgUcVHgIksb3z2glATTHF9fj4CMBI=
