export const COMPLETE_INTRO = 'COMPLETE_INTRO';

//contacts
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_FAVORITE_CONTACT = 'ADD_FAVORITE_CONTACT';
export const REMOVE_FAVORITE_CONTACT = 'REMOVE_FAVORITE_CONTACT';

//general
export const CHANGE_WALLET_TYPE = 'CHANGE_WALLET_TYPE';
export const CHANGE_DEVICE_NAME = 'CHANGE_DEVICE_NAME';
export const FOCUS_WALLET = 'FOCUS_WALLET';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';

//wallet
export const DELETE_WALLET = 'DELETE_WALLET';
export const EDIT_WALLET = 'EDIT_CONTACT';
export const ADD_WALLET = 'ADD_WALLET';
