export const COMPLETE_INTRO = 'COMPLETE_INTRO';

//contacts
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_FAVORITE_CONTACT = 'ADD_FAVORITE_CONTACT';
export const REMOVE_FAVORITE_CONTACT = 'REMOVE_FAVORITE_CONTACT';
